services:
  db:
    image: postgres:latest
    container_name: my-cms-postgres-container
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data:
